language: node_js
node_js:
  - 
cache: yarn
script:
  - yarn lint
    #- yarn test
node_js:
  - "6.4.0"
after_success:
  - test $TRAVIS_PULL_REQUEST = false && test $TRAVIS_BRANCH = "ap/travis" && yarn build
