export const AUTHENTICATION = {
  SIGN_OUT: 'AUTHENTICATION.SIGN_OUT',
  SIGN_OUT_SUCCESS: 'AUTHENTICATION.SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'AUTHENTICATION.SIGN_OUT_FAILURE',

  SIGN_IN: 'AUTHENTICATION.SIGN_IN',
  SIGN_IN_SUCCESS: 'AUTHENTICATION.SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'AUTHENTICATION.SIGN_IN_FAILURE',

  REFRESH: 'AUTHENTICATION.REFRESH',
  REFRESH_SUCCESS: 'AUTHENTICATION.REFRESH_SUCCESS',
  REFRESH_FAILURE: 'AUTHENTICATION.REFRESH_FAILURE',

  BOOTSTRAP: 'AUTHENTICATION.BOOTSTRAP',
  BOOTSTRAP_SUCCESS: 'AUTHENTICATION.BOOTSTRAP_SUCCESS',
  BOOTSTRAP_FAILURE: 'AUTHENTICATION.BOOTSTRAP_FAILURE',
}

export const ARTIST_INVITES = {
  LOAD: 'ARTIST_INVITES.LOAD',
  LOAD_SUCCESS: 'ARTIST_INVITES.LOAD_SUCCESS',
  LOAD_FAILURE: 'ARTIST_INVITES.LOAD_FAILURE',

  LOAD_TOTAL_SUBMISSIONS: 'ARTIST_INVITES.LOAD_TOTAL_SUBMISSIONS',
  LOAD_TOTAL_SUBMISSIONS_SUCCESS: 'ARTIST_INVITES.LOAD_TOTAL_SUBMISSIONS_SUCCESS',
  LOAD_TOTAL_SUBMISSIONS_FAILURE: 'ARTIST_INVITES.LOAD_TOTAL_SUBMISSIONS_FAILURE',

  LOAD_DAILY_SUBMISSIONS: 'ARTIST_INVITES.LOAD_DAILY_SUBMISSIONS',
  LOAD_DAILY_SUBMISSIONS_SUCCESS: 'ARTIST_INVITES.LOAD_DAILY_SUBMISSIONS_SUCCESS',
  LOAD_DAILY_SUBMISSIONS_FAILURE: 'ARTIST_INVITES.LOAD_DAILY_SUBMISSIONS_FAILURE',

  LOAD_TOTAL_PARTICIPANTS: 'ARTIST_INVITES.LOAD_TOTAL_PARTICIPANTS',
  LOAD_TOTAL_PARTICIPANTS_SUCCESS: 'ARTIST_INVITES.LOAD_TOTAL_PARTICIPANTS_SUCCESS',
  LOAD_TOTAL_PARTICIPANTS_FAILURE: 'ARTIST_INVITES.LOAD_TOTAL_PARTICIPANTS_FAILURE',

  LOAD_DAILY_IMPRESSIONS: 'ARTIST_INVITES.LOAD_DAILY_IMPRESSIONS',
  LOAD_DAILY_IMPRESSIONS_SUCCESS: 'ARTIST_INVITES.LOAD_DAILY_IMPRESSIONS_SUCCESS',
  LOAD_DAILY_IMPRESSIONS_FAILURE: 'ARTIST_INVITES.LOAD_DAILY_IMPRESSIONS_FAILURE',

  LOAD_TOTAL_IMPRESSIONS: 'ARTIST_INVITES.LOAD_TOTAL_IMPRESSIONS',
  LOAD_TOTAL_IMPRESSIONS_SUCCESS: 'ARTIST_INVITES.LOAD_TOTAL_IMPRESSIONS_SUCCESS',
  LOAD_TOTAL_IMPRESSIONS_FAILURE: 'ARTIST_INVITES.LOAD_TOTAL_IMPRESSIONS_FAILURE',

  LOAD_NETWORK_ACTIVITIES: 'ARTIST_INVITES.LOAD_NETWORK_ACTIVITIES',
  LOAD_NETWORK_ACTIVITIES_SUCCESS: 'ARTIST_INVITES.LOAD_NETWORK_ACTIVITIES_SUCCESS',
  LOAD_NETWORK_ACTIVITIES_FAILURE: 'ARTIST_INVITES.LOAD_NETWORK_ACTIVITIES_FAILURE',
}

export const REHYDRATE = 'persist/REHYDRATE'
