export const AUTHENTICATION = {
  SIGN_OUT: 'AUTHENTICATION.SIGN_OUT',
  SIGN_OUT_SUCCESS: 'AUTHENTICATION.SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'AUTHENTICATION.SIGN_OUT_FAILURE',

  SIGN_IN: 'AUTHENTICATION.SIGN_IN',
  SIGN_IN_SUCCESS: 'AUTHENTICATION.SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'AUTHENTICATION.SIGN_IN_FAILURE',

  REFRESH: 'AUTHENTICATION.REFRESH',
  REFRESH_SUCCESS: 'AUTHENTICATION.REFRESH_SUCCESS',
  REFRESH_FAILURE: 'AUTHENTICATION.REFRESH_FAILURE',

  BOOTSTRAP: 'AUTHENTICATION.BOOTSTRAP',
  BOOTSTRAP_SUCCESS: 'AUTHENTICATION.BOOTSTRAP_SUCCESS',
  BOOTSTRAP_FAILURE: 'AUTHENTICATION.BOOTSTRAP_FAILURE',
}

export const ARTIST_INVITES = {
  LOAD: 'ARTIST_INVITES.LOAD',
  LOAD_SUCCESS: 'ARTIST_INVITES.LOAD_SUCCESS',
  LOAD_FAILURE: 'ARTIST_INVITES.LOAD_FAILURE',
}

export const REHYDRATE = 'persist/REHYDRATE'
